name: Build and push to aws

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build project  
        run: dotnet restore; dotnet publish -o site;

      - name: Create zip package
        run: cd site; zip ../site.zip *;

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: MykryptoApi  # Se till att detta matchar din Elastic Beanstalk-applikation
          environment_name: MykryptoApi-env  # Se till att detta matchar din Elastic Beanstalk-miljö
          version_label: ${{ github.run_id }}
          region: eu-north-1  # Ange rätt region för din Elastic Beanstalk-applikation
          deployment_package: site.zip
